### ISSUE TITLE
TODO in LSD

### ISSUE THREAD

**Issue by jerrybaoo** [celinium-network/celinium#24]
- [ ] More robust IBC error process  
- [ ] MsgServer Unit test
- [ ] Gov
- [ ] Unbonding entry limit in source chain
- [ ] Reblance validators of source chain.
